[window]
opacity = 0.8
padding = { x = 10, y = 10}
blur = true
startup_mode = "Maximized"
decorations = "None"

#Only on macos
option_as_alt = "OnlyLeft"

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }

[cursor]
style = {shape = "Underline", blinking = "On"}

[mouse]
hide_when_typing = true
