# Base settings for Zed
colorize_brackets: true
vim:
  use_system_clipboard: "always"
vim_mode: true
ui_font_size: 16
buffer_font_size: 15
tab_size: 2
buffer_font_family: "CaskaydiaCove Nerd Font Mono"
hard_tabs: false
line_ending: "enforce_lf"
status_bar:
  active_language_button: true
  cursor_position_button: true
  line_endings_button: true
indent_guides:
  enabled: true
  coloring: "fixed"
telemetry:
  diagnostics: false
  metrics: false
file_types:
  JSONC:
    - "*.json.tmpl"
    - "**/zed-settings"
    - "**/zed-keymap"
    - "**/zed-tasks"
